# Generated by Django 3.2.5 on 2021-07-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000, verbose_name='متن سوال')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='mdl_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_text', models.CharField(max_length=200, verbose_name='پاسخ')),
                ('score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appscore.mdl_question')),
            ],
            options={
                'verbose_name': 'پاسخ ',
            },
        ),
    ]
