# Generated by Django 3.2.5 on 2021-07-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdl_answers',
            name='question',
        ),
        migrations.AddField(
            model_name='mdl_answers',
            name='question',
            field=models.ManyToManyField(to='appscore.mdl_Question'),
        ),
    ]
