# Generated by Django 3.2.5 on 2021-07-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appscore', '0002_auto_20210719_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdl_answers',
            name='question',
        ),
        migrations.AddField(
            model_name='mdl_answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appscore.mdl_question'),
        ),
    ]
