# Generated by Django 3.2.5 on 2021-07-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appscore', '0003_auto_20210719_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdl_Quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=30, verbose_name='سطح سوال')),
            ],
        ),
        migrations.RemoveField(
            model_name='mdl_answers',
            name='score',
        ),
        migrations.AddField(
            model_name='mdl_answers',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mdl_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appscore.mdl_quize')),
            ],
        ),
    ]
