# Generated by Django 3.2.5 on 2021-07-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appscore', '0004_auto_20210719_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appscore.mdl_quize'),
        ),
        migrations.AlterField(
            model_name='mdl_answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appscore.mdl_question'),
        ),
        migrations.AlterField(
            model_name='mdl_result',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appscore.mdl_quize'),
        ),
    ]
